name: helper_tiles
description: A package of useful ListTiles to speedup coding time
version: 0.0.7


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
